"""empty message

Revision ID: 1a89e050bfbf
Revises: 5206c209e6f7
Create Date: 2015-07-11 20:40:32.795084

"""

# revision identifiers, used by Alembic.
revision = '1a89e050bfbf'
down_revision = '5206c209e6f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
