"""empty message

Revision ID: 2ecd1c0c5743
Revises: None
Create Date: 2015-06-27 20:39:14.915603

"""

# revision identifiers, used by Alembic.
revision = '2ecd1c0c5743'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
