"""empty message

Revision ID: 31357f6f642a
Revises: 45accf09bf1a
Create Date: 2015-07-01 15:10:59.657119

"""

# revision identifiers, used by Alembic.
revision = '31357f6f642a'
down_revision = '45accf09bf1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
