"""empty message

Revision ID: 5206c209e6f7
Revises: 3c5efe71a179
Create Date: 2015-07-11 20:39:25.610568

"""

# revision identifiers, used by Alembic.
revision = '5206c209e6f7'
down_revision = '3c5efe71a179'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('about_me', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'about_me')
    op.drop_table('products')
    ### end Alembic commands ###
