"""empty message

Revision ID: 5ad3b48d44ba
Revises: 1a89e050bfbf
Create Date: 2015-07-12 00:40:01.071246

"""

# revision identifiers, used by Alembic.
revision = '5ad3b48d44ba'
down_revision = '1a89e050bfbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
